### ISSUE TITLE
After proxy, where to config the proxy or change the npm repository before docker-compose?

### ISSUE THREAD

**Issue by darshanhuang1** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#110]
Building webui
Step 1/11 : FROM node:14 AS build
 ---> b55951795ffb
Step 2/11 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 6332565b57ad
Step 3/11 : COPY package.json package-lock.json ./
 ---> Using cache
 ---> 366c1b63e128
Step 4/11 : RUN npm ci
 ---> Running in 9226bc74b6bd
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/@angular/material/-/material-11.2.13.tgz failed, reason: connect ETIMEDOUT 104.16.17.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-28T16_38_30_007Z-debug.log
ERROR: Service 'webui' failed to build: The command '/bin/sh -c npm ci' returned a non-zero code: 1

**Comment by rsdmike** [comment]
I would check out https://docs.docker.com/network/proxy/ for how to configure proxy for the docker engine and for how to pass --env options to the docker build.
