### ISSUE TITLE
Support for MongoDB in addition to PostgreSQL

### ISSUE THREAD

**Issue by gbinder2** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#117]
**Describe the bug** 

No bug, just additional feature request.  I would like the system to support MongoDB, in addition to PostgreSQL.

My expectation is that many would continue to want PostgreSQL.  But will chat with you about that.

Best, Garry

**Comment by matt-primrose** [comment]
@gbinder2 It's been a bit, but we are starting work on adding support for NoSQL (mongo compatible API).  See the issue and linked PR here: https://github.com/open-amt-cloud-toolkit/mps/issues/1063

**Comment by matt-primrose** [comment]
Released in [MPS 2.12.0](https://github.com/open-amt-cloud-toolkit/mps/releases/tag/v2.12.0)
