### ISSUE TITLE
v2.3.0 docker-compose.yml is using the latest tag for the docker images

### ISSUE THREAD

**Issue by orinem** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#129]
It was changed to 'latest' after v2.2.0 was released.

I see the v2.3.0 tag does exist on hub.docker.com.

So, is this the intent?

**Comment by rsdmike** [comment]
Hey @orinem,  What we're thinking is, our rapid releases -- the releases that we release about every 6 weeks will remain with latest as the image tag. This will make it a little easier for folks to always grab patched versions, if any, without us having to constantly update the image tags in the compose. Additionally, if you're running docker-compose up with the toolkit, its going to build fresh docker images with whatever the specified tag unless you explicitly pull. And for our LTS releases, we will pin them explicitly since we support them for a longer time. We are open to feedback on this though !

**Comment by orinem** [comment]
Well, furthering my evaluation of OpenAMT, I tried a deployment to Azure.  After working out what exactly the registry field wanted (an example in the help string would go a long way here - maybe index.docker.io) and adding "intel/oact-" to the image names, I got it up and running.

Now, I have absolutely no idea what versions are running due to the 'latest' tags.  Azure doesn't have a clue (see below).  At least with Docker Desktop, you could see what image was used.  You've created a 'moving' target... that will make bug reporting/tracking difficult if not impossible.  I.e. what was latest for mps, rps etc. when I did the deployment?  I don't know!

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/11839044/169404099-33ec554a-7745-44ec-8550-8e382cb1c435.png">

**Comment by matt-primrose** [comment]
Hey @orinem, I'm just going through old issues and I want to verify that this is working better with the changes we have implemented.  On DockerHub we have been posting both the version as well as latest when we release a new version of the components.  I think this solves the original concern, so I'm going to close this issue.   If you have additional feedback, please feel free to re-open this issue.

**Comment by orinem** [comment]
The thing is that every recent release has 'latest'.  If I clone the toolkit using the latest instructions:

```git clone https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit --branch v2.9.0 --recursive```

The docker-compose.yml has latest for everything.  If I go back a version...

```git clone https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit --branch v2.8.0 --recursive```

and look at docker-compose.yml - it has latest for everything!

As far as I can tell, it makes it difficult if not impossible to easily go back to a release - say if one was trying to work out when a bug was introduced.  Since the components tend to depend on one another, it would be a nightmare trying to use previous versions of say mps with the 'latest' of everything else.
