### ISSUE TITLE
distroless or scratch when building docker images

### ISSUE THREAD

**Issue by jaolanlo** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#145]
Wondering if distroless, scratch or similar can be used in the dockerfile when creating the docker images?

This will just copy the necessary files into the final docker image, reduce the size and the number of vulnerabilities reported by some security scans.

For golang, scratch can be used and for nodejs maybe distroless or something similar.

Let me know if you see any issue with this. Regards

CC: @rsdmike @matt-primrose

**Comment by rsdmike** [comment]
We can look at this, but we already use a slim version which has most everything removed to keep the docker image small.

**Comment by rsdmike** [comment]
We've updated RPS and MPS to use `node:16-bullseye-slim` which should reduce the amount of dependencies in the base image.
