### ISSUE TITLE
Question: Does AFP Protocol support SNI?

### ISSUE THREAD

**Issue by jclab-joseph** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#153]
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/HTMLDocuments/MPSDocuments/Intel%20AMT%20Port%20Forwarding%20Protocol%20Reference%20Manual.pdf

There is no mention of this in the AFP manual.
By the way, does AMT support TLS SNI to configure CIRA connection?
If it is supported, I am curious as to which version of CSME it supports.

**Comment by jclab-joseph** [comment]
To isolate TLS certificates from multitenant infrastructure.
Provisioning certificates are already isolatable.
However, once CIRA is provisioned, its security relies entirely on TLS.
Therefore, even if a specific tenant's certificate is leaked, this is to prevent other tenants from being affected.

**Comment by matt-primrose** [comment]
An update on this issue.  I have raised this questions and there is a discussion internally going on to add SNI support to AMT.  I will keep you updated on progress.

**Comment by gbinder2** [comment]
Greetings, I'd like to ask an additional question.  Is there a possible work around involving additional IP addresses on the server, and then assigning one certificate to each IP / FQDN?  I understand that this might not be ideal, but wanting to ensure that we have a work around given the number of legacy systems already in the wild.  Best!

**Comment by jclab-joseph** [comment]
@gbinder2 First off, we decided to use a single certificate.
And we plan to address this by allocating additional ports if requested by clients.

**Comment by matt-primrose** [comment]
@jclab-joseph It seems like you have a work around for this issue, so I'm going to close it.  If you want to re-open to discuss further, please feel free.
