### ISSUE TITLE
Add maintenance task for syncing OS hostname with AMT hostname

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#155]
**Describe the bug** 🪲
I need a way to sync the current OS hostname with the AMT hostname so that AMT will respond to network requests to the hostname when the OS is not available.

**Expected behavior**
When I run a maintenance task with RPC, I can specify that I want to sync the hostname.  RPC and RPS will then get the hostname from the OS and put that information into AMT

**Comment by tim-shockley** [comment]
linked now
