### ISSUE TITLE
RPS and MPS health check fails when vault server is setup in HA mode

### ISSUE THREAD

**Issue by rkandru** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#164]
RPS and MPS health checks fail frequently with vault health check response code 429. 
This happens when a vault cluster is setup in HA mode. In the HA mode there is a Active node and standby node. 
If the vault health check  on /sys/health endpoint reaches stand-by node **response code - 429** is sent. 
MPS and RPS services are returning vault status as unhealthy.

**To Reproduce** 🪜
Setup vault in HA mode with Active and Standby nodes behind a load balancer.
Hit the sys/health endpoint, you will get a response code - 429 when the request reaches stand-by node.
 

**Expected behavior**
A response code of 200 when the request reaches stand-by node. This can be achieved by passing parameter - standbyok

[standbyok](https://developer.hashicorp.com/vault/api-docs/system/health#standbyok) (bool: false) – Specifies if being a standby should still return the active status code instead of the standby status code. This is useful when Vault is behind a non-configurable load balancer that just wants a 200-level response. This will not apply if the node is a performance standby. 

Hashicorp documentation - 
https://developer.hashicorp.com/vault/api-docs/system/health#standbyok

**Comment by rjbrache** [comment]
Resolved per linked PRs.
