### ISSUE TITLE
Storage Redirection

### ISSUE THREAD

**Issue by brunomirandades** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#166]
Currently the application I'm collaborating on uses the Storage Redirection resources available in the Intel HLAPI:

```
// creating an amt instance
Intel.Manageability.IAMTInstance amt;

// starting the service
amt.RedirectionIDER.SetInterfaceState(true);
amt.RedirectionIDER.StartIDERCD(isoPath);

 // checking status
amt.RedirectionIDER.CurrentSessionState;

// stopping the service
amt.RedirectionIDER.StopIDER();
```

Is there anything similar available in the toolkit to cover these same usage cases? If not, is there any forecast on implementation?

**Comment by graikhel-intel** [comment]
Hi @brunomirandades

We do not support storage redirection currently but it's already in our backlog. Couple of priority items that the team is working in Q1 2023 (and potentially Q2) are support for 802.1x and TLS (i.e., TLS cert signed by a CA). We don't have a specific timeline to release this feature yet but I can work on getting this data.

As far as I understand, there are 3 different ways to get started on this
1. Using imrsdk.dll (AMT SDK uses imrsdk.dll for storage redirection)
2. Reusing IDER code from MeshCommander https://github.com/Ylianst/MeshCommander/blob/master/amt-ider-ws-0.0.1.js
3. Writing the whole USB-R/IDER/SCSI protocol from scratch

The last time we had a discussion within the team regarding storage redirection, we planned to use 2. 

I do believe IDER implementation is going to be fairly complex (given we do not plan to use imrsdk_x64.dll). That said, we appreciate any help you give with contributions.

**Comment by bwendlandt-intel** [comment]
Closing.  IDER is implemented as part of the December release!
