### ISSUE TITLE
Feature Enhancement: CIRA and/or TLS shouldn't be a requirement during profile creation.

### ISSUE THREAD

**Issue by mtpham123** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#169]
**Describe the bug** 🪲

In the OpenAMT Sample UI, when creating a provisioning profile, it currently forces to use CIRA and/or TLS(Enterprise). Many IOTG customers have older hardware that still supports none TLS. Although 80-90 percent of our customers use TLS, there are a number of customers that do not use TLS.  Currently, when they go to pilot our Open AMT solution in their private network, they are forced to use CIRA when they do not need to.

**To Reproduce** 🪜
1. Go to Profile creation in the OpenAMT Sample UI
2. Click to create a provisioning profile
3. Scroll down to save the profile
5. See error "A CIRA or TLS Config is required"

**Comment by matt-primrose** [comment]
With the console they are using to manage the devices, do they have the ability to accept self-signed certificates when connecting to AMT?

**Comment by bwendlandt-intel** [comment]
@mtpham123 Some additional info.  CIRA vs TLS validation is currently enforced by the Sample Web UI, but `non-tls` is still available directly through the RPS Profile APIs as an alternative.  By setting both `ciraConfigName` and `tlsMode` to null, it will default to `non-tls`.  [More info about this API can be found in the Create Profile API docs](https://open-amt-cloud-toolkit.github.io/docs/2.7/APIs/indexRPS/).

Here's a quick example of it via Postman:

Example of ACM, Non-TLS Profile URL and Body:
```
Example URL:
https://192.168.4.23/rps/api/v1/admin/profiles

Example ACM, Non-TLS Profile body:
{
    "profileName": "nonTLSProfile",
    "activation": "acmactivate",
    "generateRandomPassword": false,
    "generateRandomMEBxPassword": false,
    "amtPassword": "YourPassword123!",
    "mebxPassword": "YourPassword123!",
    "tags": [],
    "dhcpEnabled": true,
    "ciraConfigName": null,
    "tlsMode": null,
    "userConsent": "None",
    "iderEnabled": true,
    "kvmEnabled": true,
    "solEnabled": true,
    "wifiConfigs": []
}
```
**Make sure to set body to raw JSON as the format.**

![image](https://user-images.githubusercontent.com/74682355/214931742-7d8ce32b-de4f-43bd-bb8c-d9ff10d161c4.png)

**Don't forget to also set your Auth Token**
![image](https://user-images.githubusercontent.com/74682355/214931701-e84685db-120a-4c13-980f-bcece20086f9.png)


This is the expected successful RPC output using v2.5.0:
```
C:\rpc-go>rpc25 activate -u wss://192.168.4.23/activate -n -profile nonTLSProfile
time="2023-01-26T12:18:17-07:00" level=info msg="connecting to wss://192.168.4.23/activate"
time="2023-01-26T12:18:17-07:00" level=info msg="connected to wss://192.168.4.23/activate"
time="2023-01-26T12:19:01-07:00" level=info msg="Status: Admin control mode."
time="2023-01-26T12:19:01-07:00" level=info msg="Network: Wired Network Configured. "
time="2023-01-26T12:19:01-07:00" level=info msg="CIRA: "
time="2023-01-26T12:19:01-07:00" level=info msg="TLS: Failed to add trusted root certificates"
```
