### ISSUE TITLE
Device is getting activated( Provisioning) with the new AMT password given at the time of profile creation.

### ISSUE THREAD

**Issue by kalakatx** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#17]
1.Device is getting activated( Provisioning) with the new AMT password given at the time of profile creation. Tried to login to MEBX screen with the new password, unable to login with the new password but accepting old password. 
2.Also if we have MEBX and using that in BIOS and at config creations then why do we need AMT password.

**Comment by rsdmike** [comment]
For 1) what version are you using, and when you say "old password" do you mean the default MEBx password from the manufacturer? or a previous password used from a different profile
For 2) MEBX and AMT Password are two different things.  MEBX is just the password to get into the ME Bios Extensions menu when you are sitting in front of the device.  AMT Password is just used for remote access.

**Comment by matt-primrose** [comment]
Closing issue as resolved in 1.1
