### ISSUE TITLE
Docker Swarm Deployment

### ISSUE THREAD

**Issue by rjbrache** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#174]
**Describe the bug** 🪲
Docker Swarm deployment per the documentation (https://open-amt-cloud-toolkit.github.io/docs/2.8/Tutorials/Scaling/docker-swarm/) no longer results in a successful deployment.  It appears the generated swarm.yml file is no longer in a format supported by current Docker engine versions.

**To Reproduce** 🪜
Tested with Docker Desktop.
Ensure you have the latest docker engine and docker compose installed (both are part of Docker Desktop).  Follow the steps detailed in the above link.  The step deploying the stack ("docker stack deploy...") will result in... "unsupported Compose file version: 1.0"

**Expected behavior**
A successful swarm deployment which can be used to manage devices.

**Comment by bwendlandt-intel** [comment]
Docker swarm is no longer a production recommendation
