### ISSUE TITLE
init.sql file is not generating the rpsdb in postgres when installing standalone services without containers.

### ISSUE THREAD

**Issue by Rafael910401** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#187]
Hi,
I found an issue when installing the Open AMT Cloud Toolkit without the docker-compose.yml file, I mean installing the services one by one. The happens specifically with the RPS component. Basically to generate the rpsdb in postgres we use the **init.sql f**ile located in the **./data** folder, what I found so far, the script **.init.sql** doesn't have the query: 

`CREATE DATABASE rpsdb;`

**The problem can be reproduced with the following steps:**
1.- Modify the file **./rps/.rpsrc** with the configuration required for your RPS component. Be sure to setup the connection string for postgresql.
2.- Execute the shell command `psql -U <username> -h localhost -f ./data/init.sql`
3.- Install the rps component using `npm install` (Don't forget to change directory to **rps** folder)
4.- Start the rps component using `npm start` and you will se the error, the RPS component is not finding the **rpsdb**.

**Expected Behavior:**
![image](https://user-images.githubusercontent.com/50605327/236242944-565af00a-1301-4bd3-9a14-69ca2c6ec957.png)

**An easy fix, that should be included in the file *./data/.init.sql**
To address this issue, I found a solution:
1.- Adding the following query after the **6 line**: `SELECT 'CREATE DATABASE rpsdb' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'rpsdb')\gexec`
2.- Execute the shell command `psql -U <username> -h localhost -f ./data/init.sql`
3.-  Start the rps component using `npm start`.

**Result:**
![image](https://user-images.githubusercontent.com/50605327/236245048-33c16c0f-1d40-432e-9e1c-e9d5ddedd7c8.png)

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: OS - Ubuntu Server 22.04 LTS (Stand-alone without containers)
 - Node Version: v18.16.0
 - Component & Version: RPS 2.9.0

**Comment by matt-primrose** [comment]
@Rafael910401 if you are feeling up for it, go ahead and file a PR for the change and the team will take a look at it
