### ISSUE TITLE
Power policy should be selected at BIOS under Intel®ME Power Control screen -Mobile: On in So, MEWake in S3, S4-5 –Power Package 2 for performing device poweron/off operations

### ISSUE THREAD

**Issue by kalakatx** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#19]
Once the device is provisioned and connected to MPS Server, I have tried to power down and it was successful. But I was not able to power up the device.
solution: Enabling the power policy with "Mobile: On in So, MEWake in S3, S4-5 –Power Package 2" this option at BIOS fixed the issue.

**Comment by rsdmike** [comment]
@bwendlandt-intel I'm thinking this could go in the troubleshooting guide? Need to ensure power policy is correct in BIOS. 

@kalakatx If you could provide a screenshot of the bios setting you are talking about, and the hardware you are using that would be helpful.

**Comment by matt-primrose** [comment]
@kalakatx can you also provide the platform you are using (make and model)?  Also, AMT version would be helpful as well.

**Comment by matt-primrose** [comment]
@bwendlandt-intel is this issue resolved?

**Comment by vyshali-chitikeshi** [comment]
closed due to no updates.
