### ISSUE TITLE
If the server system(MPS,RPS is running) is restarted, API’s calls are failing with “Internal Server Error 500”.

### ISSUE THREAD

**Issue by kalakatx** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#20]
<img width="951" alt="AMT_Internal_server" src="https://user-images.githubusercontent.com/79848678/109506112-492f9a80-7ac3-11eb-8819-19dc8412676e.PNG">

**Comment by kalakatx** [comment]
This scenario is happening when we restart the AMT microservices and tries to access the AMT Web UI by hitting 3000 port.  No error observed in logs. I will try to reproduce once again and attach the logs.

**Comment by matt-primrose** [comment]
No update for 20 days.  @kalakatx if you are still seeing this issue, please feel free to re-open and attach logs so we can see what is going on.
