### ISSUE TITLE
Incorporate "Mesh Commander" non-CIRA communication within OAMTCT for On-Prem installations

### ISSUE THREAD

**Issue by ctmorris88** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#200]
**Describe the feature request**

For customer with On-prem installations of Open AMT Cloud Toolkit (OAMTCT), it would be nice to have the option to have non-CIRA based communication and also support key functionality found within the Mesh Commander.

The ask:
1.  Add in non-CIRA based connection support like Mesh Commander
2.  Add in key features of Mesh Commander such as IDE-USE Redirection, OCR, RSE and Wake Alarms

**To Reproduce** 🪜

**Expected behavior**
Would have similar functionality to Mesh Commander today.

**Screenshots** 🖼️

**AMT Device (please complete the following information):** 🖥️

**Service Deployment (please complete the following information):** ⛈️

**Additional context**

**Comment by bwendlandt-intel** [comment]
Hey @ctmorris88!

We'll treat this issue mainly for the 1st ask you've made (i.e. non-CIRA based connection support aka 'Direct Connect').

For your 2nd ask, please see these existing issues for latest tracking:
Storage Redirection: #166 
OCR: #133 
RSE: https://github.com/open-amt-cloud-toolkit/mps/issues/915

Wake alarms are already supported as of v2.5.0, please see our [API Documentation for more info on those](https://app.swaggerhub.com/apis-docs/rbheopenamt/mps/2.8.0#/AMT/get_api_v1_amt_alarmOccurrences__guid_).
<br>
Please try to limit issues to one feature/bug/request as it makes it much easier for others to search and find information as well as our own tracking in the team.
Thank you!

**Comment by bwendlandt-intel** [comment]
For support for non-CIRA based connections, take a look at our new tool, [Console](https://github.com/open-amt-cloud-toolkit/console).
