### ISSUE TITLE
Ability Open toggle User Consent off/on 

### ISSUE THREAD

**Issue by mtpham123** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#203]
**Describe the bug** 🪲

**To Reproduce** 🪜

**Expected behavior**

**Screenshots** 🖼️

**AMT Device (please complete the following information):** 🖥️
 - OS: [e.g. Linux Kernel & Version]
 - AMT Version: [e.g. 11.8.5, 12.0.45]
 - AMT Configuration Mode: [e.g. Admin Control Mode or Client Control Mode]
 - Network Configuration [e.g. Dynamic IP or Static IP]

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: [e.g. Azure, Docker, K8s]
 - Node Version: [e.g. LTS 14]
 - Component & Version: [e.g. RPS 2.0.0]

**Additional context**

**Comment by bwendlandt-intel** [comment]
Hi @mtpham123 , can you provide some more information and clarification about what you are looking for exactly? How would you imagine this working in comparison to how the toolkit functions today?

**Comment by bwendlandt-intel** [comment]
No problem, thanks! Closed.
