### ISSUE TITLE
CIRA Password

### ISSUE THREAD

**Issue by gfrankliu** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#205]
In openamt UI, when creating CIRA config, the [doc](https://open-amt-cloud-toolkit.github.io/docs/2.10/GetStarted/createCIRAConfig/) only shows "Username" (default "admin") but where do I set the Password? Is this the username/password that remote systems use to connect CIRA to the openamt server?  When I used the [rpc cli](https://github.com/open-amt-cloud-toolkit/rpc-go) to activate, it doesn't seem to have a way to provide CIRA username/password to use when communicating with open amt server.
```
sudo ./rpc activate -u wss://my-server-url/activate -n -profile my-profile
time="2023-06-02T19:29:11Z" level=info msg="connecting to wss://my-server-url//activate"
time="2023-06-02T19:29:11Z" level=info msg="wss://my-server-url//activate"
time="2023-06-02T19:29:12Z" level=info msg="connected to wss://my-server-url//activate"
time="2023-06-02T19:29:30Z" level=error msg="Failed to activate in admin control mode."
```

Looking at the server side, rps logs shows HTTP/401 Unauthorized:

```
...
Current state of Activation Machine: "GET_GENERAL_SETTINGS"
ONEVENT:
{
  type: 'error.platform.send-generalsettings',
  data: {
    protocolVersion: 'HTTP/1.1',
    statusCode: 401,
    statusMessage: 'Unauthorized',
    headersSize: 295,
    bodySize: 690,
    headers: [ [Object], [Object], [Object], [Object], [Object] ],
    body: {
      contentType: 'text/html',
      text: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" >\n' +
        '<html><head><link rel=stylesheet href=/styles.css>\n' +
        '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n' +
        '<title>Intel&reg; Active Management Technology</title></head>\n' +
        '<body>\n' +
        '<table class=header>\n' +
        '<tr><td valign=top nowrap>\n' +
        '<p class=top1>Intel<font class=r><sup>&reg;</sup></font> Active Management Technology\n' +
        '<td valign="top"><img src="logo.gif" align="right" alt="Intel">\n' +
        '</table>\n' +
        '<br />\n' +
        '<h2 class=warn>Log on failed. Incorrect user name or password, or user account temporarily locked.</h2>\n' +
        '\n' +
        '<p>\n' +
        '<form METHOD="GET" action="index.htm"><h2><input type=submit value="Try again">\n' +
        '</h2></form>\n' +
        '<p>\n' +
        '\n' +
        '</body>\n' +
        '</html>\n'
    }
  },
  toString: [Function (anonymous)]
}
Current state of Activation Machine: "ERROR"
ONEVENT:
{
  type: 'done.invoke.error-machine',
  data: undefined,
  toString: [Function (anonymous)]
}
Current state of Activation Machine: "GET_GENERAL_SETTINGS"
ONEVENT:
{
  type: 'done.invoke.send-generalsettings',
  data: [Object: null prototype] {
    Envelope: [Object: null prototype] {
      '$': [Object: null prototype],
      Header: [Object: null prototype],
      Body: [Object: null prototype]
    }
  },
  toString: [Function (anonymous)]
}
Current state of Activation Machine: "IPS_HOST_BASED_SETUP_SERVICE"
ONEVENT:
{
  type: 'done.invoke.send-hostbasedsetup',
  data: [Object: null prototype] {
    Envelope: [Object: null prototype] {
      '$': [Object: null prototype],
      Header: [Object: null prototype],
      Body: [Object: null prototype]
    }
  },
  toString: [Function (anonymous)]
}
Current state of Activation Machine: "ADD_NEXT_CERT_IN_CHAIN"
ONEVENT:
{
  type: 'done.invoke.send-certificate',
  data: [Object: null prototype] {
    Envelope: [Object: null prototype] {
      '$': [Object: null prototype],
      Header: [Object: null prototype],
      Body: [Object: null prototype]
    }
  },
  toString: [Function (anonymous)]
}
Current state of Activation Machine: "ADD_NEXT_CERT_IN_CHAIN"
ONEVENT:
{
  type: 'done.invoke.send-certificate',
  data: [Object: null prototype] {
    Envelope: [Object: null prototype] {
      '$': [Object: null prototype],
      Header: [Object: null prototype],
      Body: [Object: null prototype]
    }
  },
  toString: [Function (anonymous)]
}
Current state of Activation Machine: "ADMIN_SETUP"
2023-06-02T19:29:30.955Z info: Activation_State_Machine - {
	"method": "error",
	"apiKey": "xxxxx",
	"appVersion": "2.10.0",
	"protocolVersion": "4.0.0",
	"status": "failed",
	"message": "{\"Status\":\"Failed to activate in admin control mode.\"}",
	"payload": null,
	"tenantId": ""
}
ONEVENT:
{
  type: 'done.invoke.send-adminsetup',
  data: [Object: null prototype] {
    Envelope: [Object: null prototype] {
      '$': [Object: null prototype],
      Header: [Object: null prototype],
      Body: [Object: null prototype]
    }
  },
  toString: [Function (anonymous)]
}
Current state of Activation Machine: "FAILED"
ONDONE:
{
  type: 'done.invoke.activation-machine',
  data: undefined,
  toString: [Function (anonymous)]
}
```

**Comment by bwendlandt-intel** [comment]
Hi @gfrankliu ,

You are correct, CIRA username/password are the credentials used to verify that connection.  This is handled internally by MPS for you. The password is set one of two ways:
1. By default, a random password is generated automatically during device configuration and stored in Vault alongside other device passwords (AMT/MEBX passwords) in the `/devices` directory.
2. Or, a static CIRA password can be manually set through the APIs directly using the `password` field. [See CIRAConfig POST API](https://app.swaggerhub.com/apis-docs/rbheopenamt/rps/2.11.0#/CIRA/CreateCIRAConfig).

<br>

However, this is separate from the activation issue. The CIRA credentials aren't used till after successful device activation and configuration.  The `Log on failed. Incorrect user name or password, or user account temporarily locked.` error is typically thrown for RPC's `deactivate` or `maintenance` commands when they are executed on an AMT device that RPS does not have the credentials stored for (i.e. the device was configured to another RPS server or dev mode Vault was restarted) and can be solved using the `-f` flag.

Can you please share some additional info about the AMT device and state from `sudo ./rpc amtinfo`? Has this device been used/configured before?  Thanks!

**Comment by gfrankliu** [comment]
```
$ sudo ./rpc amtinfo
Version			: 12.0.64
Build Number		: 1551
SKU			: 16392
UUID			: <redacted>
Control Mode		: pre-provisioning state
DNS Suffix		: ext.mytestdomain.com
DNS Suffix (OS)		: controller.lan
Hostname (OS)		: thebox-studio
RAS Network      	: outside enterprise
RAS Remote Status	: not connected
RAS Trigger      	: user initiated
RAS MPS Hostname 	: 
---Wired Adapter---
DHCP Enabled 		: true
DHCP Mode    		: passive
Link Status  		: up
IP Address   		: 0.0.0.0
MAC Address  		: 84:8b:cd:40:38:20
---Wireless Adapter---
DHCP Enabled 		: false
DHCP Mode    		: passive
Link Status  		: down
IP Address   		: 0.0.0.0
MAC Address  		: 00:00:00:00:00:00
```

No, I haven't had any luck in configuring it with CIRA. I also tried meshcentral but that failed too https://github.com/Ylianst/MeshCentral/issues/5176

**Comment by gfrankliu** [comment]
> The CIRA credentials aren't used till after successful device activation and configuration. 

Are you saying activation is anonymous and anyone can activate their AMT with my server without a password? Is that a security concern if I have my server in the cloud open to Internet? Can this be secured?

**Comment by gfrankliu** [comment]
As for security, by default RPS and WebUI runs on port 443, and CIRA on 4433, is it possible to split RPS and WebUI to two different ports? We can have three types of IP ranges for firewall:

- Lab/Factory: we would need to allow RPS port since activate is normally done here.
- Office: we would need to allow WebUI port since support personnel are here.
- Final remote locations for the AMT devices: we probably need to open CIRA port to ALL, since those locations are not known. Since CIRA connection requires authentication, it is likely safe to do so.

**Comment by bwendlandt-intel** [comment]
I believe the answer to these questions were resolved via email, so I'll just mention them here too for any others that find their way here.

#### Port 443

Yes, the ports can be split onto different ports.  This would require a customization to Kong which would involve changing both the `kong.yaml` and `docker-compose.yml` files.

#### Activation Error

For ACM activation, users can create their own self-signed provisioning certificate rather than a 3rd party CA.  But, the hash of the certificate must be added manually to AMT (via MEBx or USB).

The activation error was caused due to the generated self-signed provisioning certificate being incorrect.  In this specific case, the provisioning certificate was missing the Server Authentication ("SSL Server") OID.  It should also include the Intel AMT unique OID (2.16.840.1.113741.1.2.3) and the OU value in the Subject field should be "Intel(R) Client Setup Certificate".

<br><br>

@gfrankliu I'll close this issue now.  Of course, if another error pops up or you have more general questions, please file a new issue or reach out to the team [via our Discord](https://discord.gg/yrcMp2kDWh) or via email directly, if confidential.  Thank you!
