### ISSUE TITLE
Change request GET:alarmOccurrences

### ISSUE THREAD

**Issue by msbreton** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#239]
**Describe the bug** 🪲
Feature / Change request
Would like GET:alarmOccurrences API to return "Interva"l in minutes vs. AMT SDK format ie. PT10M, so that it matches POST:alarmOccurrences "Interval" input requirements, which is in minutes.

Also, suggest Swagger be updated to reflect that POST:alarmOccurrences "Interval" input expectation is in minutes and not AMT SDK format.

**To Reproduce** 🪜

**Expected behavior**

**Screenshots** 🖼️

**AMT Device (please complete the following information):** 🖥️
 - OS: [e.g. Linux Kernel & Version]
 - AMT Version: [e.g. 11.8.5, 12.0.45]
 - AMT Configuration Mode: [e.g. Admin Control Mode or Client Control Mode]
 - Network Configuration [e.g. Dynamic IP or Static IP]

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: [e.g. Azure, Docker, K8s]
 - Node Version: [e.g. LTS 14]
 - Component & Version: [e.g. RPS 2.0.0]

**Additional context**

**Comment by graikhel-intel** [comment]
This should be resolved with this PR https://github.com/open-amt-cloud-toolkit/mps/pull/1656. Fix is available in the latest MPS release.
