### ISSUE TITLE
Hardcoded MPS port "3000" in docker-compose file

### ISSUE THREAD

**Issue by kalakatx** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#24]
Hardcoded MPS port in docker-compose file and also in MPS Dockerfile.

**Comment by rsdmike** [comment]
If you are referring to the EXPOSE commands in the MPS Dockerfile, those act more as a documentation for what ports are used by default and doesn't actually publish the port. Checkout the documentation here for more information: https://docs.docker.com/engine/reference/builder/#expose 

For the Hardcoded MPS Port - I see a couple issues with in our master branch that need to be resolved in that mainly we should not be changing the port inside the container and only the port for which is exposed. This is something that will be addressed in the next release.

**Comment by kalakatx** [comment]
While we are integrating AMT setup with other microservices(ESH RI related recipe) in that case one of the microservice uses "3000" port giving conflict to AMT setup (All these microservices including AMT will be deployed in the same machine).

If we change the exposed port from 3000 to some other will that impact or creates any issue with the below command in docker-compose.yml
      command: >
      /bin/bash -c "
        while ! nc -z mps 3000;
        do
          echo waiting for mps;
          sleep 5;
        done;
        echo MPS Running!;
        node ./dist/Index.js;
      "

**Comment by rsdmike** [comment]
Gotcha, ok yeah so the issue stems from the 2nd point in my earlier post. We'll take care of it.

>I see a couple issues with in our master branch that need to be resolved in that mainly we should not be changing the port inside the container and only the port for which is exposed. This is something that will be addressed in the next release.
