### ISSUE TITLE
Create a user account for handling administrative tasks

### ISSUE THREAD

**Issue by mechris1** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#245]
Tasks like:

- [x] Updating Changelog
- [x] Tagging releases
- [x] Updating versions in the code
- [x] Create new GitHub account (Rosie)
- [x] Get access to account as a contributor.

**Comment by Craig-Spencer-12** [comment]
Jira ticket submitted for contributor access. Waiting for response.
