### ISSUE TITLE
Can't register AMT in ACM

### ISSUE THREAD

**Issue by lg0killer** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#250]
**Describe the bug** 🪲
I can register an AMT 16 device with CCM but when I try to do ACM it tells me it failed to activate in Admin mode

**To Reproduce** 🪜
1. Create a new setup with a valid domain certificate (we used Digicert)
2. Click on devices and add new device
3. Run the command provided: 
  * sudo ./rpc activate -u wss://<rps_server>/activate -n --profile <profile_name> -v
[rps.log](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/files/13393203/rps.log)
[admin.log](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/files/13393204/admin.log)

**Expected behavior**
I expect the rpc command to tell me successfully connected to rpc in admin mode

**Screenshots** 🖼️
![rps_output](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/assets/10009132/b5684862-5067-4caa-b386-974a664e1a00)
![rpc_output](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/assets/10009132/f23ac66e-7d0f-4673-9490-3c964f467bd1)

**AMT Device (please complete the following information):** 🖥️
 - OS: Ubuntu 22.04 LTS
 - AMT Version: 16.1.27
 - AMT Configuration Mode: Admin Control Mode (currently pre-provisioning state)
 - Network Configuration Dynamic IP

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: Docker
 - Node Version: LTS 14
 - Component & Version: RPS 2.20.0 (I think)

**Additional context**
We recently started with this. I'm not sure if there is something we need more like full internet access or other settings for our environment

**Comment by lg0killer** [comment]
The issue seems to relate to the AdminSetup command being sent to the host

**Comment by graikhel-intel** [comment]
Hi @lg0killer, Looks like the Provisioning certificate you are using for activation is missing Intel AMT OID  (2.16.840.1.113741.1.2.3). For activation to ACM, this OID is mandatory. I think you would have to go back to DigiCert and request them to issue a vPro certificate. If you need specific pointers on how to do this, please email me at ganesh.raikhelkar@intel.com and I can loop in necessary folks that can help you.

Here are the requirements for vPro Provisioning cert:
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Facquiringanintelvprocertificate.htm

Here is a doc that has steps on how to request a Provisioning Cert:
https://www.intel.com/content/www/us/en/support/articles/000055009/technologies.html

Let me know if this helps!

**Comment by lg0killer** [comment]
This issue has been resolved.

Our main problem was with our certificate and once we got the vPro OID it started working.

We have noticed that for some strange reason the devices that we used to test the setup had to be completely formatted from the BIOS side, but once we fully unprovisioned them it worked like it should

Thank you for the assistance
