### ISSUE TITLE
Failed to create profile due to missing local_wifi_sync_enabled database column

### ISSUE THREAD

**Issue by rgl** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#256]
**Describe the bug** 🪲

I'm stuck at the https://open-amt-cloud-toolkit.github.io/docs/2.17/GetStarted/createProfileACM/ step while trying to create a profile.

It's erroring with `Operation failed: profile1`, and the logs has the `ERROR:  column "local_wifi_sync_enabled" of relation "profiles" does not exist` error.

**To Reproduce** 🪜
1. Follow the docker compose guide at https://open-amt-cloud-toolkit.github.io/docs/2.17/GetStarted/setup/
2. Follow the guide up to the create profile ACM page, fill up the page, and click the `SAVE` button.
3. See it fails with `Operation failed: profile1`.

Looking at the docker compose logs, I can see:

```
kong-1       | 192.168.1.11 - - [24/Dec/2023:18:24:19 +0000] "POST /rps/api/v1/admin/profiles HTTP/2.0" 400 56 "https://192.168.1.11/profiles/new" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
db-1         | 2023-12-24 18:24:19.279 UTC [3991] ERROR:  column "local_wifi_sync_enabled" of relation "profiles" does not exist at character 391
db-1         | 2023-12-24 18:24:19.279 UTC [3991] STATEMENT:  
db-1         |          INSERT INTO profiles(
db-1         |            profile_name, activation,
db-1         |            amt_password, generate_random_password,
db-1         |            cira_config_name,
db-1         |            mebx_password, generate_random_mebx_password,
db-1         |            tags, dhcp_enabled, tls_mode,
db-1         |            user_consent, ider_enabled, kvm_enabled, sol_enabled,
db-1         |            tenant_id, tls_signing_authority, ieee8021x_profile_name, ip_sync_enabled, local_wifi_sync_enabled)
rps-1        | 2023-12-24T18:24:19.279Z error: ProfilesDb - Failed to insert AMT profile: profile1,error: column "local_wifi_sync_enabled" of relation "profiles" does not exist
rps-1        | 2023-12-24T18:24:19.280Z error: createProfile - Failed to POST: profile1,Error: Operation failed: profile1
```

**Expected behavior**

Expected it to create the profile without errors.

Also expected the error to be more prominent in the page, like in a red background, also, the save button should have turned red too. This would help because the actual error is displayed at the top of the page (which in my case, I needed to scroll up), without any visual clue.

**Screenshots** 🖼️

![image](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/assets/43356/a77d6450-e806-40df-bbc9-d4e3ff55bf33)

**AMT Device (please complete the following information):** 🖥️

N/A. I didn't even reach the device stages.

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: Docker
 - Node Version: whatever is used when we do a `git clone https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit --branch v2.17.0 --recursive`
 - Component & Version: whatever is used when we do a `git clone https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit --branch v2.17.0 --recursive`

**Additional context**

**Comment by bwendlandt-intel** [comment]
Hello, I see what is going on.  Thank you for raising this.  This is a side effect of how we've chosen to implement automation for DockerHub and do our monthly wrap up releases on Github. I'll talk with the team and see how we can avoid this going forward.

In the meantime, there are a few options you can do to workaround this:
1. Update the `docker-compose.yml` to pull RPS v2.21.2 (the last November RPS release) instead of latest https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/blob/f61a34ccedd585406abdc566dae89650d127e054/docker-compose.yml#L23
2. Pull the `main` branch of open-amt-cloud-toolkit rather than `v2.17.0`.
3. Manually modify the RPS sql script to add the required column and restart the service https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/blob/f61a34ccedd585406abdc566dae89650d127e054/data/init.sql#L64

<br>
Let us know if that resolves your issue, thanks! Sorry for the inconvenience.

**Comment by rgl** [comment]
@bwendlandt-intel I've used option 1 and it now succeeded saving the data. thank you!

please do ensure this repo, at least on the branch that is documented or has a tag, that everything uses non-latest/versioned tags.

now I'm off to the next part!

maybe you can help me :-)

I'm going to abuse this comment, please let me know if I should move this to somewhere else.

essentially, I do not want to buy any commercial certificate. for example, https://open-amt-cloud-toolkit.github.io/docs/2.17/GetStarted/createProfileACM/#create-a-profile, requires a provisioning certificate, can it be from my private CA? what is preventing AMT from trusting my private CA? do I just need to manually enroll my private CA in the AMT firmware before using this toolkit? or is something fundamentally odd with AMT CIRA that prevents this from happening?

**Comment by bwendlandt-intel** [comment]
You beat me to it as I was typing! Here's some extra context that might be helpful anyway that I had typed:

AMT has a set of existing, stored hashes from the allowed vendors that it will use as part of the verification process with the provisioning certificate.  One of those hashes must match against the certificate used during ACM activation.  You can view these in MEBx. Hence by default out of the box, a certificate from the specific 3rd party CAs is required.

You can get around this by adding your own hash of your own 'custom' provisioning certificate.  The trade-off being that it requires touching every device and makes scaling across large fleets difficult.  Pre-AMT 16 devices can add it via MEBx or USB.  AMT 16 or newer devices disable the MEBx option and it must be through USB configuration only.

As a side note, I'd recommend [joining our Discord server (accounts are free)](https://discord.gg/yrcMp2kDWh) for the quickest way for responses to questions like these!
