### ISSUE TITLE
error msg="binary.Write: some values are not fixed-sized in type int" when I execute ./rpc activate on Vpro device

### ISSUE THREAD

**Issue by OrlandoNavaZuniga** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#294]
Hello there,

We are trying to install OpenAMTCloudToolkit following the steps on the OpenAMTCloudToolkit Github site.

The development system does not have Intel AMT, only the client device have Intel AMT.
We have installed the following prerequisites on development system. 

1.- Git
2.-Docker for Linux
3.- Go* progamming lenguage.
4.-Then we set up and run the pull Docker Images.
5.- We create a configuration CIRA on Web UI.
6.- We create a CCM profile on Web UI.
7.- We build and run RPC, but when we try to run RPC on Intel AMT device, we get the following error.

time="2024-07-02T12:59:00-06:00" level=error msg="binary.Write: some values are not fixed-sized in type int"
time="2024-07-02T12:59:00-06:00" level=info msg="connecting to wss://192.168.2.69/activate"
time="2024-07-02T12:59:00-06:00" level=info msg="wss://192.168.2.69/activate"
time="2024-07-02T12:59:00-06:00" level=info msg="connected to wss://192.168.2.69/activate"
time="2024-07-02T13:01:11-06:00" level=info msg="Status: Client control mode."
time="2024-07-02T13:01:11-06:00" level=info msg="Network: Wired Network Configured"
time="2024-07-02T13:01:11-06:00" level=info msg="CIRA: Configured"
time="2024-07-02T13:01:11-06:00" level=info msg="TLS: "

We can observe the device on the WEB UI, but we can´t connect with it but the status is in dissconected.
![imagen](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/assets/173191044/6ac006f6-f7b4-41b7-bfec-6e5dd9448b3d)

**Screenshots** 🖼️
![VPRO1](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/assets/173191044/97cb7a7f-f4ae-4c6b-be2f-11fbe3f6b756)

**AMT Device (please complete the following information):** 🖥️
 - OS: [6.5.0-35-generic & Ubuntu 22.04]
 - AMT Version: [11.8.65]
 - AMT Configuration Mode: [Client Control Mode]
 - Network Configuration [192.168.2.69]

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: [Docker]
 - Node Version: [6.5.0-42-generic & Ubuntu 23.10.1]
 - Component & Version: [RPS 2.22.7]

**Comment by bwendlandt-intel** [comment]
Hello! The activation and configuration looks like it was successful. The returned `some values are not fixed-sized in type int` error should not impact this.

Unfortunately, there is a known issue for AMT v11.8.65.  I'd recommend at taking a [look at the troubleshooting steps here on how to resolve this](https://open-amt-cloud-toolkit.github.io/docs/2.23/Reference/troubleshooting/#amt-118x-not-connecting-to-sample-web-ui).

Let us know if this solves your issue and we'll close it! If not, we can take a closer look and provide some other possible suggestions.

**Comment by OrlandoNavaZuniga** [comment]
Hi, thanks for your answer.

I updated the BIOS, now I have the 11.8.95 AMT version on my NUC. I ran the command to deactivate then ran the command again to activate and this time I can connect with OpenAMT.

Thank you so much.
