### ISSUE TITLE
rpc.dll doesn't return if called multiple times when using 'amtinfo' parameter 

### ISSUE THREAD

**Issue by msbreton** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#319]
**Describe the bug** 🪲
New issue with rpc.dll version v2.23.0.  Version 2.19.0 worked correctly.
If we call rpc.dll with the 'amtinfo' parameter once, it returns correctly.
If we call it again, within the same session/context, it does not return.

**To Reproduce** 🪜
1.Call rpc.dll 'amtinfo' once - returns normally
2. Call rpc.dll 'amtinfo' again (int he same session/context) - never returns

Note: This worked correctly /w rpc.dll version 2.19.0

**Expected behavior**
rpc.dll 'amtinfo' should return regardless of how many times it's called int he same session/contact.

**Screenshots** 🖼️

**AMT Device (please complete the following information):** 🖥️
 - OS: [e.g. Linux Kernel & Version]
 - AMT Version: [e.g. 11.8.5, 12.0.45]
 - AMT Configuration Mode: [e.g. Admin Control Mode or Client Control Mode]
 - Network Configuration [e.g. Dynamic IP or Static IP]

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: [e.g. Azure, Docker, K8s]
 - Node Version: [e.g. LTS 14]
 - Component & Version: [e.g. RPS 2.0.0]

**Additional context**

**Comment by graikhel-intel** [comment]
Closing this issue as we were able to successfully call amtinfo multiple times during testing (using the sample C# code).
