### ISSUE TITLE
Question ¿How can we configure OpenAMT to access the Web UI from outside the network?

### ISSUE THREAD

**Issue by OrlandoNavaZuniga** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#325]
Hello there! 😄

We have a complete installation of OpenAMT on a server.

We are configuring "Device on" to access clients that are outside the network.

For this we need to access to the Web UI of OpenAMT from outside the network. We want to know if it is possible.
If it´s possible we want to know how we can configure it.

AMT Device (please complete the following information): 🖥️

    OS: [6.5.0-35-generic & Ubuntu 22.04]
    AMT Version: [11.8.95]
    AMT Configuration Mode: [Client Control Mode]
    Network Configuration [192.168.2.83]

Service Deployment (please complete the following information): ⛈️

    Deployment Type: [Docker]
    Node Version: [6.5.0-42-generic & Ubuntu 23.10.1]
    Component & Version: [RPS 2.22.7]

**Comment by bwendlandt-intel** [comment]
For this to work, you'd have to expose all of the services publicly, not just the Sample Web UI.

You would need to configure forwarding and/or DNS for incoming traffic. Kong is our reverse proxy so once traffic is routed to there, Kong will route it to the correct service (MPS/RPS/etc). This could also be swapped for alternatives like Traefik or Istio, whatever your preference for an API gateway.

A lot of this logic is done for you if you choose to use one of the container services from a cloud provider like Azure ACI, AWS ECI, or Alibaba ECS. Cloud providers solve the networking through the use of configured security groups and virtual private clouds (VPCs). Going through a provider offers easy scale.

If you choose to use Docker for production, I'd recommend looking into Docker Swarm for ease of scaling containers and managing them.

Any additional info you can provide on how you have your servers setup, your existing architecture, and network would be helpful. If not here, feel free to share it privately at bryan.wendlandt@intel.com

Thanks!

**Comment by bwendlandt-intel** [comment]
Closing as answered. Please reopen if you have a follow-on question or comment. Thanks!
