### ISSUE TITLE
Scaling- KVM shows white screen 

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#39]
In scaling environment i.e. deploying multiple instances of mps, rps, mps-web on azure with kubernetes, noticed that KVM shows white screen instead of amt device's remote desktop.

**Comment by matt-primrose** [comment]
@vyshali-chitikeshi is this issue resolved in 1.4?

**Comment by vyshali-chitikeshi** [comment]
Issue resolved in 1.5, closing.
