### ISSUE TITLE
Scaling- Connecting to SOL does not work correctly

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#40]
In scaling environment i.e. deploying multiple instances of mps, rps, mps-web on azure with kubernetes, noticed that connecting to SOL does not work correctly. It appears that its trying to connect to KVM when user clicks on 'connect to sol'.

**Comment by matt-primrose** [comment]
@vyshali-chitikeshi is this issue resolved in 1.4?

**Comment by vyshali-chitikeshi** [comment]
Issue resolved in 1.5, closing.
